### ISSUE TITLE
Georgian ქართული text in Kannada weeklypedia edition

### ISSUE THREAD

**Issue by yogiks** [hatnote/weeklypedia#12]
In [this week's Kannada edition](http://weekly.hatnote.com/archive/kn/20150821/weeklypedia_20150821.html), instead of Kannada ಕನ್ನಡ, Georgian ქართული text is displayed. Below is the snapshot -
![kn](https://cloud.githubusercontent.com/assets/6291913/9410371/8d1cde10-483d-11e5-8e12-872459b29ab9.png)

**Comment by slaporte** [comment]
Oh no! It's fixed in the archives. Thanks for catching that.
