### ISSUE TITLE
lv.wikipedia.org / Latvian support

### ISSUE THREAD

**Issue by papuass** [hatnote/weeklypedia#14]
Hi! We would appreciate Latvian Wikipedia version, as we are enjoying top.hatnote.com already :)

**Comment by slaporte** [comment]
It's set up and ready to go. You can sign up here: http://eepurl.com/b0V-yj The first issue will go out next Friday if someone signs up!

If you want to help translate the interface too, you can make a copy of [this file](https://github.com/hatnote/weeklypedia/blob/master/weeklypedia/issue_templates/strings/en_strings.yaml).
