### ISSUE TITLE
Support Telugu wikipedia

### ISSUE THREAD

**Issue by arjunaraoc** [hatnote/weeklypedia#16]
Please add support for Telugu wikipedia.

**Comment by slaporte** [comment]
We now have a list for Telugu Wikipedia: http://eepurl.com/b3EjMn

Enjoy!

Can you share this with the local community? The first issue will go out next Friday. If you are able to help translate Weeklypedia entirely into Telugu, you can make a copy of [this file](https://github.com/hatnote/weeklypedia/blob/master/weeklypedia/issue_templates/strings/en_strings.yaml) and I'll set that up too.
