### ISSUE TITLE
Please add Occitan language

### ISSUE THREAD

**Issue by jpgine** [hatnote/weeklypedia#18]

**Comment by slaporte** [comment]
Hey @jpgine, yes I can add Occitan Wikipedia. Sorry for taking so long to reply. Are you still interested in subscribing?

Could you help us translate the template? You can find instructions [here](https://github.com/hatnote/weeklypedia/blob/master/weeklypedia/issue_templates/strings/en_strings.yaml).

**Comment by jpgine** [comment]
Here in Catalan:

# ------------------
# Weeklypedia
# Si voleu traduir el bolletí Weeklypedia, comenceu amb una còpia
# d'aquest fitxer i deixeu-nos una nota a:
# https://github.com/hatnote/weeklypedia/issues
# -------------------------------------------------
-----------------------------

# -----------
# Introducció
# -------------------------------------------------
-----------------------------

head_title:> -
   the WEEKLYPEDIA ({full_lang_name}, número {issue_number})
body_title:> -
    <em>the</ em> WEEKLYPEDIA
description:> -
    Una llista dels articles més modificats de la Wikipèdia i
    discussions de la darrera setmana.
delivery_description: Lliurat cada divendres per correu electrònic.
home_link: Pàgina inicial
archive_link: "{local.full_lang_name} arxius d'edició"
issue_label: Número {issue_number}, {local.date}
language_label: ({local.full_lang_name} edició de la Wikipèdia)
intro:> -
    Ei! Benvinguts al nostre resum setmanal de l'activitat de la Wikipèdia.
# -----------
# Article de la secció
# -------------------------------------------------
-----------------------------
articles_heading: Articles

articles_summary: >-
    Aquesta setmana, {total_users|ci} autors han fet {edits|ci} canvis a
    {títols|ci} diferents articles.
articles_intro: els 20 millors articles de la setmana

diff_count: "{edits|ci} canvis"
diff_author_count: per {users} autors

# -----------
# Secció d'articles nous
# -------------------------------------------------
-----------------------------

new_articles_head: Nous articles
# new_articles_summary: # TOT
new_articles_intro:> -
    Els deu articles modificats més activament creats durant la darrera
setmana
# -----------
# Secció de discussió
# -------------------------------------------------
-----------------------------

encapçalament de discussions: discussions
# discussions_summary: # TODO
discussions_intro: les discussions més actives

# -----------
# Estadístiques de la secció
# -------------------------------------------------
-----------------------------

discussions_heading: Estatístiques
stats_intro: Alguns números de la setmana passada
user_edit_counts:> -
    {stats.users|ci} membres registrats i
    {stats.anon_ip_count|ci} els membres no registrats han fet
{stats.edits|ci}
    canvis a {stats.titles|ci} articles
anon_edit_counts:> -
    Els membres no registrats han fet edicions {stats.anon_edits|ci}
    {stats.anon_titles|ci} articles
bot_edit_counts:> -
    {stats.bot_count|ci} que els robots han fet
    {stats.bot_edits|ci} canvis a {stats.bot_titles|ci} articles
# -----------
# Secció inferior
# -------------------------------------------------
-----------------------------

signup_link: Registra-t'hi!
about_heading: A propòsit
about_text:> -
    Aquest projecte recupera una llista dels canvis recents de la setmana
mitjançant <a
    href="http://tools.wmflabs.org/">Wikimedia Tool Labs</a>, i
    lliura missatges de correu electrònic amb MailChimp. Codi i més
informació <a
    href="https://github.com/hatnote/weeklypedia"> disponible a
    GitHub</a>. Creat per <a href="https://github.com/slaporte">Stephen
    LaPorte</a> i <a href="https://github.com/mahmoud">Mahmoud
    Hashemi</a>.
blog_link: Més informació al blog Hatnote
learn_more:> -
    Més informació sobre el bolletí <a href="http://weekly.hatnote.com">
Weeklypedia</a>

2018-06-10 2:16 GMT+01:00 Stephen LaPorte <notifications@github.com>:

**Comment by Jfblanc** [comment]
Here the occitan (languedocian) version.

# ------------------ 
# Weeklypedia 
# Se volètz traduire lo bulletin Weeklypedia, començatz amb una còpia 
# d'aquel fichièr e laissatz-nos un messatge sus:
# https://github.com/hatnote/weeklypedia/issues 
# ------------------------------------------------- ----------------------------- 
# ----------- 
# Introduccion 
# ------------------------------------------------- ----------------------------- head_title:> - la WEEKLYPÈDIA ({full_lang_name}, numèro {issue_number}) body_title:> - <em>la</ em> WEEKLYPÈDIA description:> - Una lista dels articles mai modificats de la Wikipèdia e de las discussions de la setmana passada. delivery_description: Distribuït cada divendres per corrièr electronic. home_link: Pagina iniciala archive_link: "{local.full_lang_name} archius d'edicion" issue_label: Numèro {issue_number}, {local.date} language_label: ({local.full_lang_name} edicion de la Wikipèdia) intro:> - Òu! Benvenguts al nòstre resumit setmanièr de l'activitat de la Wikipèdia. 
# ----------- 
# Article de la seccion 
# ------------------------------------------------- ----------------------------- articles_heading: Articles articles_summary: >- Aquela setmana, {total_users|ci} autors an fach {edits|ci} cambiaments a {títols|ci} diferents articles. articles_intro: los 20 melhors articles de la setmana diff_count: "{edits|ci} cambiaments" diff_author_count: per {users} autors 
# ----------- 
# Seccion d'articles novèls 
# ------------------------------------------------- ----------------------------- new_articles_head: Articles novèls 
# new_articles_summary: 
# TOT new_articles_intro:> - Los dètz articles modificats mai activament creats la setmana passada 
# ----------- 
# Seccion de discussion 
# ------------------------------------------------- ----------------------------- entèsta de discussions: discussions 
# discussions_summary: 
# TODO discussions_intro: las discussions mai activas 
# ----------- 
# Estadisticas de la seccion 
# ------------------------------------------------- ----------------------------- discussions_heading: Estadisticas stats_intro: Qualques chifras de la setmana passada user_edit_counts:> - {stats.users|ci} membres enregistrats e {stats.anon_ip_count|ci} membres pas enregistrats an fach {stats.edits|ci} cambiaments a {stats.titles|ci} articles anon_edit_counts:> - Los membres pas enregistrats an modificat {stats.anon_edits|ci} {stats.anon_titles|ci} articles bot_edit_counts:> - {stats.bot_count|ci} que los robòts an fach {stats.bot_edits|ci} cambiaments a {stats.bot_titles|ci} articles 
# ----------- 
# Seccion inferiora 
# ------------------------------------------------- ----------------------------- signup_link: S'enregistrar! about_heading: Qu'es aquò about_text:> - Aquèste projècte recupera una lista dels cambiaments recents de la setmana mercé als <a href="http://tools.wmflabs.org/">Wikimedia Tool Labs</a>, e distribuís de messatges electronics amb MailChimp. Còde e mai <a href="https://github.com/hatnote/weeklypedia"> disponibles sus GitHub</a>. Creat per <a href="https://github.com/slaporte">Stephen LaPorte</a> i <a href="https://github.com/mahmoud">Mahmoud Hashemi</a>. blog_link: Mai sul blog Hatnote learn_more:> - Mai sul bulletin <a href="http://weekly.hatnote.com"> Weeklypèdia</a>

**Comment by slaporte** [comment]
Thanks, @jpgine and @Jfblanc! 

Here are links, if you want to share the newly translated lists:

 * Sign up for Catalan: http://eepurl.com/M7HU9
 * Sign up for Occitan: http://eepurl.com/dxJIYf

The next issue will go out on Friday.
