### ISSUE TITLE
The same content in the newsletters

### ISSUE THREAD

**Issue by Ainali** [hatnote/weeklypedia#20]
[#159](http://weekly.hatnote.com/archive/sv/20170331/weeklypedia_20170331.html), [#158](http://weekly.hatnote.com/archive/sv/20170324/weeklypedia_20170324.html) and [#157](http://weekly.hatnote.com/archive/sv/20170317/weeklypedia_20170317.html) have all the same content in Swedish.

**Comment by mahmoud** [comment]
I guess it speaks to Stephen and my schedule that this has snuck past us for so long (that and I completely missed the Wikimania CFP despite my best efforts). I opened a labs issue for the underlying cause: https://phabricator.wikimedia.org/T161915

Thank you for your reporting (and patience)!
