### ISSUE TITLE
Same most edited new article two weeks in a row

### ISSUE THREAD

**Issue by Ainali** [hatnote/weeklypedia#24]
Weeklypedia 252 and 253 in Swedish have the same most edited new article: sv:Gatutåg. The second week it should not be a new article anymore.

**Comment by mahmoud** [comment]
Sigh, it's a bummer, but for some reason the toolsforge service died and was not restarted by the job grid over there. I've restarted it now and the service is running. I have all reasons to expect that the next issue and many more in the future will work fine, but I need to come up with a better scheme for reliability to avoid this happening again. Sorry about that!

**Comment by mahmoud** [comment]
And thank you for reporting the issue here! I tend to respond faster on GitHub than Twitter. :)
