### ISSUE TITLE
Wrong date and articles in issue 331

### ISSUE THREAD

**Issue by Ainali** [hatnote/weeklypedia#31]
The date in both the [English](https://weekly.hatnote.com/archive/en/20200717/weeklypedia_20200717.html) and Swedish letter is 7 July, and the content is exactly the same as in issue [330](https://weekly.hatnote.com/archive/en/20200710/weeklypedia_20200710.html).

**Comment by mahmoud** [comment]
Ah, nuts, this is due to the toolforge URL migration. Shame we already published 330, I believe the issue is fixed now, thanks to your heads up. I'll add it to the backlog to do better alerting to avoid this in future.
