### ISSUE TITLE
Portuguese language version

### ISSUE THREAD

**Issue by massula** [hatnote/weeklypedia#34]
Please.

**Comment by mahmoud** [comment]
Sure! We'll first need help of you or another Portuguese language author who can help us translate the interface. You can make a copy of [this file](https://github.com/hatnote/weeklypedia/blob/master/weeklypedia/issue_templates/strings/en_strings.yaml) to translate, and we'll take care of the rest.

You can find several examples of completed translations in [the merged pull requests](https://github.com/hatnote/weeklypedia/pulls?q=is%3Apr+is%3Aclosed). Thanks in advance!

**Comment by massula** [comment]
Nice! I will make it in the next days, and let You know.

**Comment by massula** [comment]
Done!

**Comment by slaporte** [comment]
Thank you!

**Comment by massula** [comment]
Thank you all!
