### ISSUE TITLE
ur.wikipedia.org

### ISSUE THREAD

**Issue by mshuaibnadwi** [hatnote/weeklypedia#4]
Hi :) I would like to add urdu wikipedia in this list. Plz add it, I can help translate it. Thanks

**Comment by slaporte** [comment]
Hi @mshuaibnadwi,

We added Urdu -- you can sign up [here](http://eepurl.com/bsmG1P). Enjoy!

**Comment by mshuaibnadwi** [comment]
Thanks a lot!

**Comment by mahmoud** [comment]
@MuhammadShuaib if you're feeling motivated, you can also create a translation similar to #8, #9, and #10.

**Comment by slaporte** [comment]
You can find the phrases that need translation [here](https://github.com/hatnote/weeklypedia/blob/master/weeklypedia/issue_templates/strings/en_strings.yaml). Thanks!
