### ISSUE TITLE
zh.wikipedia.org

### ISSUE THREAD

**Issue by Pseric** [hatnote/weeklypedia#5]
Hi,

Please add zh.wikipedia.org as Chinese Wikipedia Edition,

thanks for help! :)

Regards,
Pseric

**Comment by slaporte** [comment]
Hi @Pseric,

We now have [Chinese Weeklypedia](http://eepurl.com/bsmGhT). If you know anyone who wants updates on Chinese Wikipedia activity, please share the link!

**Comment by slaporte** [comment]
@Pseric any interest helping us translate [these phrases](https://github.com/hatnote/weeklypedia/blob/master/weeklypedia/issue_templates/strings/en_strings.yaml), so that the newsletter can be entirely in Chinese?

**Comment by Pseric** [comment]
@slaporte Ok, no problem. I'll do it later.

**Comment by shangkuanlc** [comment]
I volunteer to translate these into traditional chinese (taiwan)!

however, i am not a programmer and a totally a newbie to github, can anyone
show me how to use it or indicate which phrases need to be translated and
which are not, so i can work on those phrases.


Liang

2015-08-18 10:20 GMT+08:00 Stephen LaPorte <notifications@github.com>:
