### ISSUE TITLE
Oddity in number of edits in the Swedish versions top article

### ISSUE THREAD

**Issue by Ainali** [hatnote/weeklypedia#59]
[This week](https://weekly.hatnote.com/archive/sv/20210402/weeklypedia_20210402.html), the article Älvenäs is listed as the top article with 68 edits by 1 user and [last week](https://weekly.hatnote.com/archive/sv/20210326/weeklypedia_20210326.html) it was the same article with 88 edits by 1 user. However, looking at [the history](https://sv.wikipedia.org/w/index.php?title=%C3%84lven%C3%A4s&action=history) I can only add up the edits to just over 50 in the entire year. What is going on here?

**Comment by slaporte** [comment]
It looks like one user made a lot of small edits:
 - [week of 2021-04-02](https://quarry.wmflabs.org/query/53852)
 - [week of 2021-03-26](https://quarry.wmflabs.org/query/53853)

The counts look correct to me, but [here is weeklypedia's query](https://quarry.wmflabs.org/query/53851) in case you can spot anything that isn't working right!

**Comment by Ainali** [comment]
Hm, yes it does. I must have ended up on the second page of the history by mistake somehow when trying to count.
