### ISSUE TITLE
Weeklyishpedia

### ISSUE THREAD

**Issue by slaporte** [hatnote/weeklypedia#6]
If there is a Labs outage on a Friday, it's possible Weeklypedia will run with Thursdays data. It should note when sending an issue without a full week's data.

**Comment by mahmoud** [comment]
Well, to be clear, it's always **a** week of data, delivered **weekly**. But yes, there may be some overlap between weeks based on availability of Wikipedia services. I'm not sure how publicly we want to advertise it but we can include a message to the effect of "Data fetched at <date>."
