### ISSUE TITLE
kn.wikipedia.org

### ISSUE THREAD

**Issue by yogiks** [hatnote/weeklypedia#7]
Hi, 

Please add [Kannada](http://kn.wikipedia.org) wikipedia to the list. And I can help translate it.

thanks,
yogi

**Comment by yogiks** [comment]
Its been quite few days now, can the developers kindly look into this.? Please let me know if there's anything to be done from my side.

cc: @mahmoud @slaporte

**Comment by slaporte** [comment]
Hey @yogiks, I'll take a look.

We don't support translation (yet) for the email template, but I'll let you know when that's an option too. Thanks!

**Comment by slaporte** [comment]
We've set up a [Kannada version of Weeklypedia](http://eepurl.com/buxugf). The first issue will go out this Friday! 

If you know other Kannada Wikipedians, could you share the link with them?

**Comment by yogiks** [comment]
Thanks a lot! Will share this with other Kannada Wikipedians through mailing list and WP:VP. :smile:

**Comment by mahmoud** [comment]
Great! Be sure to share an example of the sorts of information that will be published: http://weekly.hatnote.com/archive/kn/20150731/weeklypedia_20150731.html

**Comment by yogiks** [comment]
Sure, have shared the links [here](https://lists.wikimedia.org/pipermail/wikikn-l/2015-August/000676.html) and [here](https://kn.wikipedia.org/wiki/%E0%B2%B5%E0%B2%BF%E0%B2%95%E0%B2%BF%E0%B2%AA%E0%B3%80%E0%B2%A1%E0%B2%BF%E0%B2%AF:%E0%B2%85%E0%B2%B0%E0%B2%B3%E0%B2%BF_%E0%B2%95%E0%B2%9F%E0%B3%8D%E0%B2%9F%E0%B3%86#Weeklypedia_.E0.B2.88.E0.B2.97_.E0.B2.95.E0.B2.A8.E0.B3.8D.E0.B2.A8.E0.B2.A1_.E0.B2.B5.E0.B2.BF.E0.B2.95.E0.B2.BF.E0.B2.AA.E0.B3.80.E0.B2.A1.E0.B2.BF.E0.B2.AF.E0.B2.97.E0.B3.86_.E0.B2.B2.E0.B2.AD.E0.B3.8D.E0.B2.AF) with the community. 
Thank you once again. :smiley:

**Comment by slaporte** [comment]
@yogiks We are ready for translation help, if you have time! Could you translate [these phrases](https://github.com/hatnote/weeklypedia/blob/master/weeklypedia/issue_templates/strings/en_strings.yaml) into Kannada?

**Comment by yogiks** [comment]
@slaporte Thanks for the reminder! Have done the [translation](https://github.com/yogiks/weeklypedia/blob/master/weeklypedia/issue_templates/strings/kn_strings.yaml) and created the [PR](https://github.com/hatnote/weeklypedia/pull/11). Please have a look at it.

**Comment by slaporte** [comment]
Hi @yogiks , I've added the localized template to the archive (see [here](http://weekly.hatnote.com/archive/kn/20150821/weeklypedia_20150821.html)), and we'll use it for the next issue. How does this look? Thanks for all your help!

**Comment by yogiks** [comment]
@slaporte Looks awesome! However, observed a small typo in ```articles_heading: ``` text. It should have been ಲೇಖನಗಳು instead of ಲೇಖನೆಗಳು. Can it corrected now or should I create another pull request?

**Comment by yogiks** [comment]
@slaporte have made a PR #13 to fix this. Please see to it.

**Comment by slaporte** [comment]
I've merged in the pull request. Thanks for updating it!
